services:
  server:
    build: .
    ports:
      - "80:80"
    environment:
      PORT: "80"
      HOST_PROC: "/host/proc"
      HOST_SYS: "/host/sys"
      HOST_ETC: "/host/etc"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro
    pid: host
    restart: unless-stopped
